version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: .
        WORKING_DIR: /src
    ports:
      - "88:9000"
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/src
    command: ["node_modules/.bin/nodemon", "server"]
  redis:
    image: redis
